### ISSUE TITLE
Cannot retrieve data on receiving SMS

### ISSUE THREAD

**Issue by rockycabaero** [globelabs/gl-docs#1]
How do I get the data? 
I tried using $_GET, $_POST, $_REQUEST still no luck.

**Comment by rockycabaero** [comment]
nevermind.. i got it using
file_get_contents("php://input");
//closing issue

**Comment by rockyru** [comment]
Hi, can you show your full code para don sa pag retrieve ng data on receiving sms? thanks

**Comment by rockyru** [comment]
Hi Michelle,

Sa may notify uri ko ilalagay yang code na yan ano po?

**Comment by amsantos** [comment]
Hi, Ruther.

Yes, in the script that is hosted in your server. The NotifyURI is the
public address e.g. http://abc.com/samplescript.php

samplescript.php will contain the snippet I've sent.

**Comment by rockyru** [comment]
I've tried, pero blank lang po ba talaga yung response non? nag print_r ako nung isa print_r($msg); blank po yung page.

**Comment by oninmalasan** [comment]
Hi Ruther,


Is your Notify URI up and running? May I also ask what telco are you testing?

**Comment by rockyru** [comment]
Yes sir, up and running siya. eto po yung url http://vote.bwsi.com.ph/notifier.php
Smart and Globe po tinetest ko.

**Comment by oninmalasan** [comment]
Then you shouldn't have any problem. You should be able to access or view all the contents of your Notify URI. For the record, can you post here how you access the contents of your Redirect URI?

**Comment by rockyru** [comment]
<?php

//check if server is a POST request
if ($_SERVER['REQUEST_METHOD'] == 'POST'){
	
                 //open input stream, since this is a PUSH transaction from our server
	$in = file_get_contents("php://input");	
	
	$line = urldecode($in);
	$j = json_decode($line);

	

	$parts = $j->inboundSMSMessageList->totalNumberOfPendingMessage;
	$batch = $j->inboundSMSMessageList->numberOfMessagesInThisBatch;
	$num = $j->inboundSMSMessageList->inboundSMSMessage[0]->senderAddress;
	$msg = $j->inboundSMSMessageList->inboundSMSMessage[0]->message;
	$destinationAddress = $j->inboundSMSMessageList->inboundSMSMessage[0]->destinationAddress;

	print_r($msg);
}

?>

Ganyan sir.

**Comment by oninmalasan** [comment]
I mean how do you access the contents of your endpoint? Not how you manipulate whats inside.

**Comment by rockyru** [comment]
Ganito po sir
`$q = Curl::to('http://vote.bwsi.com.ph/notifier.php')
                
                 ->asJson()
                 ->post();

        dd($q);`

**Comment by oninmalasan** [comment]
May I ask what happens on this part of the code you provided?

**Comment by rockyru** [comment]
null ung na da die dump sir.
