### ISSUE TITLE
Can't get access token

### ISSUE THREAD

**Issue by andresitodeguzman** [globelabs/gl-docs#7]
The url https://developer.globelabs.com.ph/oauth/access_token returns a 404.

**Comment by andresitodeguzman** [comment]
@EliMariaaaa use POST request etc.

**Comment by EliMariaaaa** [comment]
@andresitodeguzman yeah, I got it working. Thanks!

**Comment by jsl13** [comment]
@EliMariaaaa sir can you please have a step by step process on how you solved this problem po? I am having same problem "The url https://developer.globelabs.com.ph/oauth/access_token returns a 404."

Thanks! I'm trying to learn Globe Labs API on SMS.

**Comment by salacsoft** [comment]
@andresitodeguzman sir can you give tips on how to get the code needed to parameter to get access token, i tried to use the short code but its not working.

**Comment by andresitodeguzman** [comment]
SOLUTION FOR GETTING ACCESS TOKEN THROUGH WEB FORM:
Here's how to get the access token from the url,
1. Get the code sent through GET
` $code = $_GET['code']; `

2. The url shows 404 for GET requests, probably they forgot to setup the appropriate error. Use POST to send the code to retrieve the access token. I used CURL on this one. See that I needed to pass the app_id, app_secret and the code I got.
```php
$stmt = http_build_query(array(
        "app_id" => $glb_app_id,
        "app_secret" => $glb_app_secret,
        "code" => $code
));

$curl = curl_init();
curl_setopt($curl, CURLOPT_URL, "https://developer.globelabs.com.ph/oauth/access_token");
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl, CURLOPT_POST, 1);
curl_setopt($curl, CURLOPT_POSTFIELDS, $stmt);
$result = curl_exec($curl);
curl_close($curl);

$result = json_decode($result,true); // Contains array("subscriber_number"=>09123456789,"access_token"=>"someRandomToken12345")
```
3. Handle & use the results accordingly.
```php
$subscriber_number = $result['subscriber_number'];
$access_token = $result['access_token'];
```

**Comment by andresitodeguzman** [comment]
SOLUTION FOR GETTING ACCESS TOKEN THROUGH SMS:
This solution applies to those who would not use a web form (pure SMS systems/apps/services). On this one, the access token will be sent to the redirect URI you provided in the developer dashboard so you better prep that up for picking up registrations from users.

As per the Globe Labs API documentation (https://github.com/globelabs/gl-docs), the redirect URI will receive the following data, access_token and subscriber_number. This is identical to the web form but instead no need to send a request to get it. Just make sure to handle that. But in addition, you also need to handle unsubscription by your user.

```php
// It's better to add a mechanism to check if requesting party is from globe labs. You can do this by checking the url if it is actually from globe labs. Also see if it uses https. Better to be safe than sorry.

// for subscription
if(!empty($_GET['access_token'])){
       // Handle data
        $access_token = $_GET['access_token'];
        $subscriber_number = $_GET['access_token'];

       // Check if user is registered or not
        if($ProprietaryClass->subscriberExists($subscriber_number) == false){
              $ProprietaryClass->registerSubscriber($access_token, $subscriber_number);
       } else {
             // Check if the access code stored is still equal to the one stored. Not required but highly recommended. 
             $subscriber_info = $ProprietaryClass->getSubsciberInfoByNumber($subscriber_number);
             if($subscriber_info['access_token'] !== $access_token) $ProprietaryClass->updateAccessToken($access_token, $subscriber_number);
       }
}
```
